# Dockerfile
FROM python:3.11-slim

WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt \
    && apt-get update \
    && apt-get install -y curl telnet
EXPOSE 8000
CMD [ "python", "main.py" ]