# Generated by Django 3.1.8 on 2025-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('FINISHED', 'Finished'), ('CONFIRMED', 'Confirmed'), ('INVOICED', 'Invoiced'), ('CANCELED', 'Canceled'), ('DENIED', 'Denied'), ('REJECTION_REQUESTED', 'Rejection Requested'), ('REJECTED', 'Rejected'), ('EXCHANGE_REQUESTED', 'Exchange Requested')], default='SCHEDULED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('doctor_id', 'date', 'time')},
            },
        ),
    ]
