# Generated by Django 4.2.21 on 2025-05-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dispensed_quantity',
        ),
    ]
