# Generated by Django 4.2.21 on 2025-05-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_remove_prescriptionitem_dispensed_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('PENDING_DISPENSING', 'Pending Dispensing'), ('DISPENSED', 'Dispensed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
    ]
